curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node1", "node1"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8651
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node2", "node2"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8652
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node3", "node3"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8653
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node4", "node4"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8654
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node5", "node5"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8655
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node6", "node6"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8656
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node7", "node7"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8657
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node8", "node8"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8658
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node9", "node9"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8659
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node10", "node10"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8660
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node11", "node11"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8661
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node12", "node12"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8662
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node13", "node13"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8663
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node14", "node14"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8664
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node15", "node15"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8665
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node16", "node16"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8666
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node17", "node17"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8667
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node18", "node18"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8668
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node19", "node19"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8669
curl --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["node20", "node20"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8670
