[parity] 
chain = "21chain.json" 
base_path = "node8"

[network] 
port = 30308
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8658
apis =["all"]

[websockets]
disable = false 
port = 8758

[account]
password = ["node8/password.txt"]
unlock = ["0x008272a8cfd2d3d0f3edc823b1bb729cb73f09db"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x008272a8cfd2d3d0f3edc823b1bb729cb73f09db"
engine_signer = "0x008272a8cfd2d3d0f3edc823b1bb729cb73f09db"

