[parity] 
chain = "21chain.json" 
base_path = "node18"

[network] 
port = 30318
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8668
apis =["all"]

[websockets]
disable = false 
port = 8768

[account]
password = ["node18/password.txt"]
unlock = ["0x00a6a2655ad6707e925bb6949a933f05690288bb"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x00a6a2655ad6707e925bb6949a933f05690288bb"
engine_signer = "0x00a6a2655ad6707e925bb6949a933f05690288bb"

