[parity] 
chain = "21chain.json" 
base_path = "node17"

[network] 
port = 30317
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8667
apis =["all"]

[websockets]
disable = false 
port = 8767

[account]
password = ["node17/password.txt"]
unlock = ["0x004edc8b40e4c8210e7c25cd9236f2461bbf1ada"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x004edc8b40e4c8210e7c25cd9236f2461bbf1ada"
engine_signer = "0x004edc8b40e4c8210e7c25cd9236f2461bbf1ada"

