[parity] 
chain = "21chain.json" 
base_path = "node2"

[network] 
port = 30302
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8652
apis =["all"]

[websockets]
disable = false 
port = 8752

[account]
password = ["node2/password.txt"]
unlock = ["0x002e28950558fbede1a9675cb113f0bd20912019"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x002e28950558fbede1a9675cb113f0bd20912019"
engine_signer = "0x002e28950558fbede1a9675cb113f0bd20912019"

