[parity] 
chain = "21chain.json" 
base_path = "node20"

[network] 
port = 30320
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8670
apis =["all"]

[websockets]
disable = false 
port = 8770

[account]
password = ["node20/password.txt"]
unlock = ["0x0049555fbcd81a300481f8bab352f2bd0679140e"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x0049555fbcd81a300481f8bab352f2bd0679140e"
engine_signer = "0x0049555fbcd81a300481f8bab352f2bd0679140e"

