[parity] 
chain = "21chain.json" 
base_path = "node14"

[network] 
port = 30314
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8664
apis =["all"]

[websockets]
disable = false 
port = 8764

[account]
password = ["node14/password.txt"]
unlock = ["0x002db24c08ed9397bc77a554e55f80d56be7b15f"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x002db24c08ed9397bc77a554e55f80d56be7b15f"
engine_signer = "0x002db24c08ed9397bc77a554e55f80d56be7b15f"

