[parity] 
chain = "21chain.json" 
base_path = "node9"

[network] 
port = 30309
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8659
apis =["all"]

[websockets]
disable = false 
port = 8759

[account]
password = ["node9/password.txt"]
unlock = ["0x001ce0f63558e2fe10806d132d64d2b2f63ef64e"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x001ce0f63558e2fe10806d132d64d2b2f63ef64e"
engine_signer = "0x001ce0f63558e2fe10806d132d64d2b2f63ef64e"

