[parity] 
chain = "21chain.json" 
base_path = "node3"

[network] 
port = 30303
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8653
apis =["all"]

[websockets]
disable = false 
port = 8753

[account]
password = ["node3/password.txt"]
unlock = ["0x00a94ac799442fb13de8302026fd03068ba6a428"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x00a94ac799442fb13de8302026fd03068ba6a428"
engine_signer = "0x00a94ac799442fb13de8302026fd03068ba6a428"

