[parity] 
chain = "21chain.json" 
base_path = "node1"

[network] 
port = 30301
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8651
apis =["all"]

[websockets]
disable = false 
port = 8751

[account]
password = ["node1/password.txt"]
unlock = ["0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2"
engine_signer = "0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2"

