[parity] 
chain = "21chain.json" 
base_path = "node7"

[network] 
port = 30307
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8657
apis =["all"]

[websockets]
disable = false 
port = 8757

[account]
password = ["node7/password.txt"]
unlock = ["0x003f3b1f635b2dd9a4518c33098e5f72214d6a1e"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x003f3b1f635b2dd9a4518c33098e5f72214d6a1e"
engine_signer = "0x003f3b1f635b2dd9a4518c33098e5f72214d6a1e"

