[parity] 
chain = "21chain.json" 
base_path = "node13"

[network] 
port = 30313
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8663
apis =["all"]

[websockets]
disable = false 
port = 8763

[account]
password = ["node13/password.txt"]
unlock = ["0x00734b960d1edd54e50192e47acfdc8af0fbbd20"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x00734b960d1edd54e50192e47acfdc8af0fbbd20"
engine_signer = "0x00734b960d1edd54e50192e47acfdc8af0fbbd20"

