[parity] 
chain = "21chain.json" 
base_path = "node4"

[network] 
port = 30304
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8654
apis =["all"]

[websockets]
disable = false 
port = 8754

[account]
password = ["node4/password.txt"]
unlock = ["0x00d4f0e12020c15487b2a525abcb27de647c12de"]

[mining]
reseal_on_txs = "none"
force_sealing = true
author = "0x00d4f0e12020c15487b2a525abcb27de647c12de"
engine_signer = "0x00d4f0e12020c15487b2a525abcb27de647c12de"

