mkdir logs
nohup   ../openethereum-3.3.4/target/debug/openethereum --max-peers 35 --config node0.toml  >logs/node0.log 2>&1 & 
nohup   ../openethereum-3.3.4/target/debug/openethereum --max-peers 35 --config node1.toml  >logs/node1.log 2>&1 & 
nohup   ../openethereum-3.3.4/target/debug/openethereum --max-peers 35 --config node2.toml  >logs/node2.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node3.toml  >logs/node3.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node4.toml  >logs/node4.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node5.toml  >logs/node5.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node6.toml  >logs/node6.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node7.toml  >logs/node7.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node8.toml  >logs/node8.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node9.toml  >logs/node9.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node10.toml  >logs/node10.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node11.toml  >logs/node11.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node12.toml  >logs/node12.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node13.toml  >logs/node13.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node14.toml  >logs/node14.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node15.toml  >logs/node15.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node16.toml  >logs/node16.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node17.toml  >logs/node17.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node18.toml  >logs/node18.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node19.toml  >logs/node19.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config node20.toml  1>logs/node20.log 2>&1 & 
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr1.toml  1>logs/usr1.log 2>&1 &
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr2.toml  1>logs/usr2.log 2>&1 &
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr3.toml  1>logs/usr3.log 2>&1 &
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr4.toml  1>logs/usr4.log 2>&1 &
nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr5.toml  1>logs/usr5.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr6.toml  1>logs/usr6.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr7.toml  1>logs/usr7.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr8.toml  1>logs/usr8.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr9.toml  1>logs/usr9.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr10.toml  1>logs/usr10.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr11.toml  1>logs/usr11.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr12.toml  1>logs/usr12.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr13.toml  1>logs/usr13.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr14.toml  1>logs/usr14.log 2>&1 &
#nohup   ../openethereum/target/debug/openethereum --max-peers 35 --config usr15.toml  1>logs/usr15.log 2>&1 &
