mkdir logs
nohup   /data/xr/openethereum-3.3.4/target/debug/openethereum --max-peers 35 --config node0.toml --tx-queue-per-sender 1000 >logs/node0.log 2>&1 & 
nohup   /data/xr/openethereum-3.3.4/target/debug/openethereum --max-peers 35 --config node1.toml --tx-queue-per-sender 1000 >logs/node1.log 2>&1 & 
nohup   /data/xr/openethereum-3.3.4/target/debug/openethereum --max-peers 35 --config node2.toml --tx-queue-per-sender 1000 >logs/node2.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node3.toml --tx-queue-per-sender 1000 >logs/node3.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node4.toml --tx-queue-per-sender 1000 >logs/node4.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node5.toml --tx-queue-per-sender 1000 >logs/node5.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node6.toml --tx-queue-per-sender 1000 >logs/node6.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node7.toml --tx-queue-per-sender 1000 >logs/node7.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node8.toml --tx-queue-per-sender 1000 >logs/node8.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node9.toml --tx-queue-per-sender 1000 >logs/node9.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node10.toml --tx-queue-per-sender 1000 >logs/node10.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node11.toml --tx-queue-per-sender 1000 >logs/node11.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node12.toml --tx-queue-per-sender 1000 >logs/node12.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node13.toml --tx-queue-per-sender 1000 >logs/node13.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node14.toml --tx-queue-per-sender 1000 >logs/node14.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node15.toml --tx-queue-per-sender 1000 >logs/node15.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node16.toml --tx-queue-per-sender 1000 >logs/node16.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node17.toml --tx-queue-per-sender 1000 >logs/node17.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node18.toml --tx-queue-per-sender 1000 >logs/node18.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node19.toml --tx-queue-per-sender 1000 >logs/node19.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config node20.toml --tx-queue-per-sender 1000 1>logs/node20.log 2>&1 & 
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr1.toml --tx-queue-per-sender 1000 1>logs/usr1.log 2>&1 &
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr2.toml --tx-queue-per-sender 1000 1>logs/usr2.log 2>&1 &
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr3.toml --tx-queue-per-sender 1000 1>logs/usr3.log 2>&1 &
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr4.toml --tx-queue-per-sender 1000 1>logs/usr4.log 2>&1 &
nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr5.toml --tx-queue-per-sender 1000 1>logs/usr5.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr6.toml --tx-queue-per-sender 1000 1>logs/usr6.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr7.toml --tx-queue-per-sender 1000 1>logs/usr7.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr8.toml --tx-queue-per-sender 1000 1>logs/usr8.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr9.toml --tx-queue-per-sender 1000 1>logs/usr9.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr10.toml --tx-queue-per-sender 1000 1>logs/usr10.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr11.toml --tx-queue-per-sender 1000 1>logs/usr11.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr12.toml --tx-queue-per-sender 1000 1>logs/usr12.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr13.toml --tx-queue-per-sender 1000 1>logs/usr13.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr14.toml --tx-queue-per-sender 1000 1>logs/usr14.log 2>&1 &
#nohup   /data/xr/openethereum/target/debug/openethereum --max-peers 35 --config usr15.toml --tx-queue-per-sender 1000 1>logs/usr15.log 2>&1 &
