#!/bin/bash

gnome-terminal -t "node1" -x bash -c "openethereum --config node1.toml;exec bash;"
gnome-terminal -t "node2" -x bash -c "openethereum --config node2.toml;exec bash;"
gnome-terminal -t "node3" -x bash -c "openethereum --config node3.toml;exec bash;"
gnome-terminal -t "node4" -x bash -c "openethereum --config node4.toml;exec bash;"
gnome-terminal -t "node5" -x bash -c "openethereum --config node5.toml;exec bash;"
gnome-terminal -t "node6" -x bash -c "openethereum --config node6.toml;exec bash;"
gnome-terminal -t "node7" -x bash -c "openethereum --config node7.toml;exec bash;"
gnome-terminal -t "node8" -x bash -c "openethereum --config node8.toml;exec bash;"
gnome-terminal -t "node9" -x bash -c "openethereum --config node9.toml;exec bash;"
gnome-terminal -t "node10" -x bash -c "openethereum --config node10.toml;exec bash;"
gnome-terminal -t "node11" -x bash -c "openethereum --config node11.toml;exec bash;"
gnome-terminal -t "node12" -x bash -c "openethereum --config node12.toml;exec bash;"
gnome-terminal -t "node13" -x bash -c "openethereum --config node13.toml;exec bash;"
gnome-terminal -t "node14" -x bash -c "openethereum --config node14.toml;exec bash;"
gnome-terminal -t "node15" -x bash -c "openethereum --config node15.toml;exec bash;"
gnome-terminal -t "node16" -x bash -c "openethereum --config node16.toml;exec bash;"
gnome-terminal -t "node17" -x bash -c "openethereum --config node17.toml;exec bash;"
gnome-terminal -t "node18" -x bash -c "openethereum --config node18.toml;exec bash;"
gnome-terminal -t "node19" -x bash -c "openethereum --config node19.toml;exec bash;"
gnome-terminal -t "node20" -x bash -c "openethereum --config node20.toml;exec bash;"
