[parity] 
chain = "21chain.json" 
base_path = "usr10"

[network] 
port = 30330
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8680
apis =["all"]

[websockets]
disable = false 
port = 8780

[account]
password = ["usr10/password.txt"]
unlock = ["0x00f2d36b1e343fdcdfcb733710944bfc1cd04413"]
