[parity] 
chain = "21chain.json" 
base_path = "usr3"

[network] 
port = 30323
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8673
apis =["all"]

[websockets]
disable = false 
port = 8773

[account]
password = ["usr3/password.txt"]
unlock = ["0x00379d1ae3b1def5241a44369397a4dadb1dff64"]
