[parity] 
chain = "21chain.json" 
base_path = "usr5"

[network] 
port = 30325
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"

[rpc]
port = 8675
apis =["all"]

[websockets]
disable = false 
port = 8775

[account]
password = ["usr5/password.txt"]
unlock = ["0x0032d84dff7be846333990d48d05db2a670089ad"]
