[parity] 
chain = "21chain.json" 
base_path = "usr7"

[network] 
port = 30327
id = 2025
reserved_only = false
reserved_peers = "myPrivateNetwork.txt"
max_peers = 30

[rpc]
port = 8677
apis =["all"]

[websockets]
disable = false 
port = 8777

[account]
password = ["usr7/password.txt"]
unlock = ["0x00d49a6f587bfa28535af292e335af82692d78d8"]
