name:                           Check

on:
  pull_request:
  push:
    branches:
      - main
      - dev
jobs:
  check:
    name:                       Check
    runs-on:                    ubuntu-16.04
    steps:
      - name:                   Checkout sources
        uses:                   actions/checkout@main
        with:
          submodules:           true
      - name:                   Install stable toolchain
        uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            stable
          profile:              minimal
          override:             true
      - name:                   Run cargo check 1/3
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked --no-default-features --verbose
      - name:                   Run cargo check 2/3
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked --manifest-path crates/runtime/io/Cargo.toml --no-default-features --verbose
      - name:                   Run cargo check 3/3
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked --manifest-path crates/runtime/io/Cargo.toml --features "mio" --verbose
      - name:                   Run cargo check evmbin
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked -p evmbin --verbose
      - name:                   Run cargo check benches
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked --all --benches --verbose
      - name:                   Run validate chainspecs
        run:                    ./scripts/actions/validate-chainspecs.sh
